[tool.pytest.ini_options]
addopts = "-v"

[tool.coverage.report]
omit = ["cgiqgispluginsandboxday/qgis_plugin_tools/*"]

[tool.ruff]
target-version = "py38"
extend = "ruff_defaults.toml"


exclude = ["cgiqgispluginsandboxday/qgis_plugin_tools"]

[tool.ruff.lint]

unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]

[[tool.mypy.overrides]]
module = "cgiqgispluginsandboxday.qgis_plugin_tools.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = ["qgis.*", "osgeo.*"]
ignore_missing_imports = true
